ldap:
  context:
    source: ldaps://directory.lyreco.com/
  search:
    base: dc=lyreco,dc=com
    filter: uid={0}
  enable: true
#management
management:
  security:
    enabled: true

server:
  port:  8090